language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install libsuitesparse-dev -y
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libblas-dev
      - liblapack-dev
python:
  - 3.6
script: python test_environment.py
